os: linux
dist: trusty
language: java
install: skip
before_script:
  - echo $JDK_PROFILE
  - echo $JVM_EXTRA_ARGS
script: mvn package -Pall-java,lgpl,examples,checkstyle,$JDK_PROFILE -DskipTests -Dmaven.javadoc.skip=true

jobs:
  include:
    - jdk: openjdk8
      before_script:
        - export JDK_PROFILE=java-8
    - jdk: openjdk11
      before_script:
      - export JVM_EXTRA_ARGS='--illegal-access=permit --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED --add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED --add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED -Djdk.tls.client.protocols=TLSv1.2'
      - export JDK_PROFILE=java-9+

before_cache:
  - rm -rfv $HOME/.m2/repository/org/apache/ignite/
cache:
  directories:
    - $HOME/.m2/repository