dist: trusty
language: java
install: skip
script: mvn package -Pall-java,lgpl,examples,checkstyle,$JDK_PROFILE -DskipTests -Dmaven.javadoc.skip=true

matrix:
  include:
    - jdk: openjdk8
      env:
        - JDK_PROFILE='java-8'
    - jdk: openjdk11
      env:
      - JVM_EXTRA_ARGS='--illegal-access=permit --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED --add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED --add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED -Djdk.tls.client.protocols=TLSv1.2'
      - JDK_PROFILE='java-9+'

before_cache:
  - rm -rfv $HOME/.m2/repository/org/apache/ignite/
cache:
  directories:
    - $HOME/.m2/repository